#################### default parameters ############################
# favicon module: https://github.com/gethugothemes/hugo-modules/tree/master/images#favicon-implementation
favicon = "images/favicon.png"
# logo module: https://github.com/gethugothemes/hugo-modules/tree/master/images#logo-implementation
logo = "images/logo.svg"
logo_darkmode = "images/logo-darkmode.svg"
# use `px` or `x` with logo_width, example: "100px".
# Note: logo_width is not work with .svg file
logo_width = "160px"
logo_height = "32px"
# if logo_webp set false, will not generate WEBP version of logo | default is true
logo_webp = true
# logo text will only show when logo is missing.
logo_text = "vince"
# navbar fixed to top
navbar_fixed = true
# theme-mode
theme_switcher = false
theme_default = "system" # available options [light/dark/system]
# Main Sections
mainSections = ["blog"]
# contact form action
contact_form_action = "#" # contact form works with [https://airform.io/] or [https://formspree.io]
# google tag manager, see https://developers.google.com/tag-manager/
google_tag_manager = "" # example: G-XXXXXXXXXX
google_adsense = ""     # example: ca-pub-xxxxxxxxxxxxxxxx
# custom script on header, example: custom_script= "<script>console.log(\"Hello World\")</script>"
# production script 
custom_script ="<script data-api=\"https://demo.vinceanalytics.com/api/event\" data-domain=\"vinceanalytics.com\">!function(){\"use strict\";var a=window.location,r=window.document,o=r.currentScript,l=o.getAttribute(\"data-api\")||new URL(o.src).origin+\"/api/event\";function s(t,e){t&&console.warn(\"Ignoring Event: \"+t),e&&e.callback&&e.callback()}function t(t,e){if(/^localhost$|^127(\\.[0-9]+){0,2}\\.[0-9]+$|^\\[::1?\\]$/.test(a.hostname)||\"file:\"===a.protocol)return s(\"localhost\",e);if((window._phantom||window.__nightmare||window.navigator.webdriver||window.Cypress)&&!window.__plausible)return s(null,e);try{if(\"true\"===window.localStorage.plausible_ignore)return s(\"localStorage flag\",e)}catch(t){}var i={},n=(i.n=t,i.u=a.href,i.d=o.getAttribute(\"data-domain\"),i.r=r.referrer||null,e&&e.meta&&(i.m=JSON.stringify(e.meta)),e&&e.props&&(i.p=e.props),new XMLHttpRequest);n.open(\"POST\",l,!0),n.setRequestHeader(\"Content-Type\",\"text/plain\"),n.send(JSON.stringify(i)),n.onreadystatechange=function(){4===n.readyState&&e&&e.callback&&e.callback({status:n.status})}}var e=window.plausible&&window.plausible.q||[];window.plausible=t;for(var i,n=0;n<e.length;n++)t.apply(this,e[n]);function p(){i!==a.pathname&&(i=a.pathname,t(\"pageview\"))}var c,u=window.history;u.pushState&&(c=u.pushState,u.pushState=function(){c.apply(this,arguments),p()},window.addEventListener(\"popstate\",p)),\"prerender\"===r.visibilityState?r.addEventListener(\"visibilitychange\",function(){i||\"visible\"!==r.visibilityState||p()}):p()}();</script>"

# local scropt
#custom_script ="<script data-api=\"http://localhost:8080/api/event\" data-domain=\"vinceanalytics.com\">!function(){\"use strict\";var r=window.location,o=window.document,s=o.currentScript,l=s.getAttribute(\"data-api\")||new URL(s.src).origin+\"/api/event\";function t(t,e){try{if(\"true\"===window.localStorage.plausible_ignore)return a=e,(i=\"localStorage flag\")&&console.warn(\"Ignoring Event: \"+i),void(a&&a.callback&&a.callback())}catch(t){}var a,i={},n=(i.n=t,i.u=r.href,i.d=s.getAttribute(\"data-domain\"),i.r=o.referrer||null,e&&e.meta&&(i.m=JSON.stringify(e.meta)),e&&e.props&&(i.p=e.props),new XMLHttpRequest);n.open(\"POST\",l,!0),n.setRequestHeader(\"Content-Type\",\"text/plain\"),n.send(JSON.stringify(i)),n.onreadystatechange=function(){4===n.readyState&&e&&e.callback&&e.callback({status:n.status})}}var e=window.plausible&&window.plausible.q||[];window.plausible=t;for(var a,i=0;i<e.length;i++)t.apply(this,e[i]);function n(){a!==r.pathname&&(a=r.pathname,t(\"pageview\"))}var p,c=window.history;c.pushState&&(p=c.pushState,c.pushState=function(){p.apply(this,arguments),n()},window.addEventListener(\"popstate\",n)),\"prerender\"===o.visibilityState?o.addEventListener(\"visibilitychange\",function(){a||\"visible\"!==o.visibilityState||n()}):n()}();</script>"
#custom_script = ""
# copyright
copyright = "Designed & Developed by [Geofrey Ernest](https://github.com/gernest)"

# Preloader
# preloader module: https://github.com/gethugothemes/hugo-modules/tree/master/components/preloader
[preloader]
enable = false
preloader = "" # use jpg, png, svg or gif format.

# Navigation button
[navigation_button]
enable = true
label = "Live Demo"
link = "#"

# search
# search module: https://github.com/gethugothemes/hugo-modules/tree/master/search
[search]
enable = true
primary_color = "#121212"
include_sections = ["blog"]
show_image = true
show_description = true
show_tags = true
show_categories = true

# announcement
# announcement module: https://github.com/gethugothemes/hugo-modules/tree/master/components/announcement
[announcement]
enable = false
expire_days = 7
content = "You must replace the **baseURL** in **hugo.toml** file when deploying, you can manage this announcement from the **params.toml** file."

# seo meta data for OpenGraph / Twitter Card
# seo module: https://github.com/gethugothemes/hugo-modules/tree/master/seo-tools/basic-seo
[metadata]
keywords = ["WebAnalytics", "Vince","alternative to googlee analytics"]
description = "Self hosted alternative to google Analytics"
author = "gernesti"
twitter = "gernesti"
image = "images/og-image.png"


# site verifications
# verification module: https://github.com/gethugothemes/hugo-modules/tree/master/seo-tools/site-verifications
[site_verification]
google = ""   # Your verification code
bing = ""     # Your verification code
baidu = ""    # Your verification code
facebook = "" # Your verification code
mastodon = "" # Your verification code

# cookies
# cookies module: https://github.com/gethugothemes/hugo-modules/tree/master/components/cookie-consent
[cookies]
enable = false
expire_days = 60
content = "This site uses cookies. By continuing to use this website, you agree to their use."
button = "I Accept"

# diagrams
[mermaid]
js_url = 'https://cdn.jsdelivr.net/npm/mermaid@latest/dist/mermaid.esm.min.mjs'

######################## sidebar widgets #########################
[widgets]
sidebar = ["categories", "tags"]


# google map
[google_map]
enable = false
map_api_key = "AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"


# Subscription
[subscription]
enable = false
# mailchimp subsciption
mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074" # replace this url with yours
mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074"
